### ISSUE TITLE
Transition between pictures is not smooth

### ISSUE THREAD

**Issue by mxmnk** [KralMarko123/berserk-meditation#1]
Every next picture jumps out, but it works smoothly if picture was loaded before.

I recommend you to test the project with disabled cache.

**Comment by KralMarko123** [comment]
Thank you for your input, I will test it out on my local machine and try to recreate the problem in order to fix it 👍

**Comment by mxmnk** [comment]
How transition works if pictures aren't loaded:

![berserk](https://user-images.githubusercontent.com/46030850/145138810-481293a8-b771-405c-9629-fb08b71ce0c2.gif)

**Comment by KralMarko123** [comment]
Closing this issue as the app has been modified to have a totally different look.
