### ISSUE TITLE
Vercel link is broken

### ISSUE THREAD

**Issue by mxmnk** [KralMarko123/berserk-meditation#2]

**Comment by KralMarko123** [comment]
I don't know if you're talking about this repository as the project is hosted on netlify. I will close this issue with this comment.

**Comment by mxmnk** [comment]
Yes, I was talking about this repository.

![IMG_20211208_111850](https://user-images.githubusercontent.com/46030850/145136797-0ec66a7b-287c-45da-a485-6fdf52a711c6.jpg)
